[package]
name = "mars_calc"
version = "0.1.0"
authors = ["David GarciÌa <9059044+Tansito@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
